# Generated by Django 6.0.5 on 2026-05-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='action_fraction',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_freemium',
        ),
    ]
