# Generated by Django 6.0.5 on 2026-05-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_remove_campaign_action_fraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='newsletter_processed',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='subscribe_newsletter',
        ),
    ]
